import type { Metadata } from 'next';
import '@/styles/global.scss';
import { CssBaseline } from '@mui/material';
import SidePanel from '@/components/sidePanel/SidePanel';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import Providers from '@/redux/Providers';

export const metadata: Metadata = {
  title: 'Spotify 2.0',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="wrapper">
            <SidePanel />
            <div className="main_window">
              <Header />
              <main className="main">
                <div className="content">{children}</div>
              </main>
              <Footer />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
